version: '3.9'  # version of docker-compose

services:
  db:
    image: mysql:latest       # loads up the image specified
    container_name: k_assignment_db    # names the container in which image will run
    ports:                      #  host port and container port
      - "3307:3306"
    environment:                    # basic environment variables - they differ in each image
      - MYSQL_USER=root                 # set up a user and a password
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password      # this is the predefined root password
      - MYSQL_DATABASE=kAssignment            # db name
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:                       # network
      - my_custom_network

  app:
    build:                              # build the image based on the Dockerfile
      dockerfile: Dockerfile
    image: app:latest                   # name the image
    container_name: kAssignment_app
    depends_on:                          # db needs to start before the ap so add dependency
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:                    # overwrite the properties file and specify url, user, password
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kAssignment
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:                     #network
      - my_custom_network

networks:                             # name the network and its type
  my_custom_network:
    driver: bridge
