insert into product (id, sku, name, description, price, company) values (1, 89566, 'Samsung S5610', 'Samsung', 41.65, 'Telit');
insert into product (id, sku, name, description, price, company) values (2, 47166, 'Samsung M130', 'Samsung', 14.67, 'verykool');
insert into product (id, sku, name, description, price, company) values (3, 34137, 'Nokia 6021', 'Nokia', 76.2, 'Oppo');
insert into product (id, sku, name, description, price, company) values (4, 15744, 'LG Optimus Pad V900', 'LG', 3.31, 'alcatel');
insert into product (id, sku, name, description, price, company) values (5, 78070, 'Panasonic T31', 'Panasonic', 44.62, 'Maxon');
insert into product (id, sku, name, description, price, company) values (6, 68764, 'Meizu M3e', 'Meizu', 78.87, 'Lenovo');
insert into product (id, sku, name, description, price, company) values (7, 99704, 'Celkon C349', 'Celkon', 69.64, 'Panasonic');
insert into product (id, sku, name, description, price, company) values (8, 69712, 'Yezz C21', 'Yezz', 61.54, 'Plum');
insert into product (id, sku, name, description, price, company) values (9, 32727, 'Nokia E51', 'Nokia', 60.32, 'Samsung');
insert into product (id, sku, name, description, price, company) values (10, 13831, 'Sony Xperia Tablet S', 'Sony', 3.56, 'Samsung');
insert into product (id, sku, name, description, price, company) values (11, 16664, 'Philips Diga', 'Philips', 76.69, 'QMobile');
insert into product (id, sku, name, description, price, company) values (12, 37140, 'Sharp 903', 'Sharp', 5.67, 'Sagem');
insert into product (id, sku, name, description, price, company) values (13, 68312, 'Huawei T161L', 'Huawei', 1.78, 'Samsung');
insert into product (id, sku, name, description, price, company) values (14, 81968, 'Nokia 103', 'Nokia', 31.17, 'alcatel');
insert into product (id, sku, name, description, price, company) values (15, 17080, 'LG K8 (2017)', 'LG', 7.57, 'Sagem');
insert into product (id, sku, name, description, price, company) values (16, 45197, 'Samsung Galaxy S9+', 'Samsung', 80.72, 'Celkon');
insert into product (id, sku, name, description, price, company) values (17, 78660, 'Samsung R730 Transfix', 'Samsung', 33.95, 'verykool');
insert into product (id, sku, name, description, price, company) values (18, 66694, 'Samsung Gear S2 classic', 'Samsung', 48.73, 'Lenovo');
insert into product (id, sku, name, description, price, company) values (19, 64162, 'Spice Mi-280', 'Spice', 23.94, 'Motorola');
insert into product (id, sku, name, description, price, company) values (20, 29513, 'Microsoft Kin One', 'Microsoft', 95.3, 'Allview');
insert into product (id, sku, name, description, price, company) values (21, 17229, 'Vodafone Smart Tab III 10.1', 'Vodafone', 30.79, 'Celkon');
insert into product (id, sku, name, description, price, company) values (22, 40682, 'OnePlus 7', 'OnePlus', 37.86, 'Samsung');
insert into product (id, sku, name, description, price, company) values (23, 29617, 'Huawei Y7a', 'Huawei', 24.56, 'LG');
insert into product (id, sku, name, description, price, company) values (24, 66057, 'Xiaomi Mi 8 SE', 'Xiaomi', 30.29, 'BlackBerry');
insert into product (id, sku, name, description, price, company) values (25, 54079, 'XOLO Q510s', 'XOLO', 36.03, 'BLU');
insert into product (id, sku, name, description, price, company) values (26, 78768, 'Samsung L310', 'Samsung', 33.58, 'Gigabyte');
insert into product (id, sku, name, description, price, company) values (27, 58003, 'i-mobile Hitz 2206', 'i-mobile', 4.69, 'Celkon');
insert into product (id, sku, name, description, price, company) values (28, 71960, 'Oppo R17', 'Oppo', 54.02, 'LG');
insert into product (id, sku, name, description, price, company) values (29, 6278, 'Oppo A3', 'Oppo', 64.25, 'Kyocera');
insert into product (id, sku, name, description, price, company) values (30, 73931, 'BLU Ultra', 'BLU', 62.76, 'Ulefone');
insert into product (id, sku, name, description, price, company) values (31, 68109, 'Micromax Canvas Unite 4', 'Micromax', 26.11, 'Meizu');
insert into product (id, sku, name, description, price, company) values (32, 96971, 'i-mobile 201', 'i-mobile', 86.02, 'Micromax');
insert into product (id, sku, name, description, price, company) values (33, 48851, 'Oppo R1001 Joy', 'Oppo', 67.23, 'Gigabyte');
insert into product (id, sku, name, description, price, company) values (34, 70017, 'Micromax Canvas Selfie 2 Q340', 'Micromax', 75.76, 'vivo');
insert into product (id, sku, name, description, price, company) values (35, 14579, 'Panasonic Eluga I2 Activ', 'Panasonic', 92.7, 'HTC');
insert into product (id, sku, name, description, price, company) values (36, 71045, 'Nokia C5-06', 'Nokia', 51.69, 'XOLO');
insert into product (id, sku, name, description, price, company) values (37, 75823, 'Samsung Galaxy Ace Style LTE G357', 'Samsung', 28.88, 'Motorola');
insert into product (id, sku, name, description, price, company) values (38, 95025, 'Sony Ericsson K220', 'Sony', 26.38, 'alcatel');
insert into product (id, sku, name, description, price, company) values (39, 65122, 'Asus Zenfone 4 Selfie ZB553KL', 'Asus', 42.68, 'alcatel');
insert into product (id, sku, name, description, price, company) values (40, 75262, 'BLU Studio Energy 2', 'BLU', 61.38, 'LG');
insert into product (id, sku, name, description, price, company) values (41, 66310, 'ZTE Obsidian', 'ZTE', 21.35, 'LG');
insert into product (id, sku, name, description, price, company) values (42, 4766, 'NEC N160', 'NEC', 80.14, 'Samsung');
insert into product (id, sku, name, description, price, company) values (43, 30779, 'Huawei P8lite ALE-L04', 'Huawei', 24.33, 'Samsung');
insert into product (id, sku, name, description, price, company) values (44, 42924, 'ZTE R221', 'ZTE', 64.14, 'LG');
insert into product (id, sku, name, description, price, company) values (45, 27830, 'BLU Tattoo', 'BLU', 90.76, 'Lava');
insert into product (id, sku, name, description, price, company) values (46, 66671, 'Samsung P300', 'Samsung', 13.34, 'Vertu');
insert into product (id, sku, name, description, price, company) values (47, 83471, 'BQ Aquaris U Lite', 'BQ', 38.63, 'Amoi');
insert into product (id, sku, name, description, price, company) values (48, 20216, 'Allview Viva H10 HD', 'Allview', 43.86, 'verykool');
insert into product (id, sku, name, description, price, company) values (49, 49846, 'Sony Ericsson C702', 'Sony', 47.93, 'Dell');
insert into product (id, sku, name, description, price, company) values (50, 97265, 'Samsung T700', 'Samsung', 35.36, 'BLU');